// Code generated by MockGen. DO NOT EDIT.
// Source: generate.go
//
// Generated by this command:
//
//	mockgen -source generate.go -destination model.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/cloudwego/eino/components/model"
	schema "github.com/cloudwego/eino/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockToolCallingChatModel is a mock of ToolCallingChatModel interface.
type MockToolCallingChatModel struct {
	ctrl     *gomock.Controller
	recorder *MockToolCallingChatModelMockRecorder
}

// MockToolCallingChatModelMockRecorder is the mock recorder for MockToolCallingChatModel.
type MockToolCallingChatModelMockRecorder struct {
	mock *MockToolCallingChatModel
}

// NewMockToolCallingChatModel creates a new mock instance.
func NewMockToolCallingChatModel(ctrl *gomock.Controller) *MockToolCallingChatModel {
	mock := &MockToolCallingChatModel{ctrl: ctrl}
	mock.recorder = &MockToolCallingChatModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolCallingChatModel) EXPECT() *MockToolCallingChatModelMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockToolCallingChatModel) Generate(arg0 context.Context, arg1 []*schema.Message, arg2 ...model.Option) (*schema.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Generate", varargs...)
	ret0, _ := ret[0].(*schema.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockToolCallingChatModelMockRecorder) Generate(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockToolCallingChatModel)(nil).Generate), varargs...)
}

// Stream mocks base method.
func (m *MockToolCallingChatModel) Stream(arg0 context.Context, arg1 []*schema.Message, arg2 ...model.Option) (*schema.StreamReader[*schema.Message], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Stream", varargs...)
	ret0, _ := ret[0].(*schema.StreamReader[*schema.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockToolCallingChatModelMockRecorder) Stream(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockToolCallingChatModel)(nil).Stream), varargs...)
}

// WithTools mocks base method.
func (m *MockToolCallingChatModel) WithTools(arg0 []*schema.ToolInfo) (model.ToolCallingChatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTools", arg0)
	ret0, _ := ret[0].(model.ToolCallingChatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTools indicates an expected call of WithTools.
func (mr *MockToolCallingChatModelMockRecorder) WithTools(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTools", reflect.TypeOf((*MockToolCallingChatModel)(nil).WithTools), arg0)
}
